### ISSUE TITLE
Errors generating cl-gss documentation

### ISSUE THREAD

**Issue by lokedhs** [quickdocs/quickdocs#28]
The package cl-gss depends on the `libgss.so` or `libgssapi_krb5.so` libraries be installed. On Ubuntu, this is provided by the `libgss-dev` package. Other Linux or Unix distributions have similar packages that provide this library.

**Comment by fukamachi** [comment]
Now the API reference of cl-gss is available at http://quickdocs.org/cl-gss/api.

**Comment by lokedhs** [comment]
Thank you!
