### ISSUE TITLE
Factor out quickdocs-parser into its own library?

### ISSUE THREAD

**Issue by eudoxia0** [quickdocs/quickdocs#32]
There are plenty of libraries out there for extracting and generating documentation from ASDF systems -- but all of them seem to do *both*. All those libraries implement their own documentation-extraction code, each with its own bugs and limitations. Since `quickdocs-parser` seems to be the most complete doc-extracting library, I'd suggesting factoring out the code into a separate library, and putting that one in Quicklisp.

**Comment by fukamachi** [comment]
Now Quickdocs uses your docparser for extracting.
