### ISSUE TITLE
www.quickdocs.org down?

### ISSUE THREAD

**Issue by kkazuo** [quickdocs/quickdocs#38]
I noticed http://www.quickdocs.org/ down.
http://quickdocs.org/ is fine.
unfortunately quicklisp search page (https://www.quicklisp.org/beta/releases.html) is pointing to the www.quickdocs.org.

DNS configuration?
- quickdocs.org has address 160.16.105.206
- www.quickdocs.org has address 49.212.47.129

**Comment by fukamachi** [comment]
Thank you for reporting.
I fixed the DNS setting.
