### ISSUE TITLE
Quickdocs.org is down, do you need any help?

### ISSUE THREAD

**Issue by svetlyak40wt** [quickdocs/quickdocs#40]
Hi!

Quickdocs.org is down and says it is under maintenance.

What is happening?

Community is [worrying](https://www.reddit.com/r/Common_Lisp/comments/6cy0kk/quickdocsorg_down/).

Do you need any help?

**Comment by fukamachi** [comment]
Oops.
I restarted the machine and it looks up now.

Unfortunately, I don't have a laptop as I'm traveling, so I can't find out
the reason of the failure.

Thank you for reporting anyway.
2017年5月26日(金) 17:30 Alexander Artemenko <notifications@github.com>:

**Comment by svetlyak40wt** [comment]
Thank you!

If you are in Moscow, you welcome!

**Comment by danielviolin0723** [comment]
It's down again and says it's under maintenance, too.
It's 9:04am on June 7th in GMT+8. 

Fukamachi San, are you still traveling?

If you are in Taiwan, you're welcome!

**Comment by Hexstream** [comment]
Seems back up right now.

**Comment by svetlyak40wt** [comment]
Closing this old issue. Thanks to https://12forks.com MVP for pointing to it.
