### ISSUE TITLE
New quicklisp projects are not showing up in quickdocs

### ISSUE THREAD

**Issue by chaitanyagupta** [quickdocs/quickdocs#41]
If I understand correctly, quickdocs should automatically add docs for any project released under quicklisp. (If that's not the case, please ignore this issue)

I wanted to go through docs for a project of mine released in the latest quicklisp update, but can't find it:

http://quickdocs.org/search?q=qbase64

In fact I can't find docs any projects released in the latest update:

http://blog.quicklisp.org/2017/12/november-2017-quicklisp-dist-update-now.html

**Comment by chaitanyagupta** [comment]
I still can't see these projects in quickdocs.org -- any update?

**Comment by Hexstream** [comment]
Thanks for the heads up and reminders, @chaitanyagupta!

Indeed the `Quicklisp: 2017-08-30` in the footer of the site tells us that the site reflects that Quicklisp dist update, which is months old.

@fukamachi Is Quickdocs considered still maintained?
It often gets cited as a resource and a number of people are relying on it...

**Comment by chaitanyagupta** [comment]
New projects are showing up now, so closing this issue.

**Comment by mihaiolteanu** [comment]
New projects are not showing up again :)

**Comment by mihaiolteanu** [comment]
Now they do, but the description is missing.

![screenshot1566926764](https://user-images.githubusercontent.com/8273519/63795118-f7c1b080-c90b-11e9-9160-f01a24d9645b.png)
